import { Geist, Geist_Mono, Cormorant_Garamond, Playfair_Display, EB_Garamond } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// Closest match to Elicyon's heading font (__elicyon_df1f4c)
const playfairDisplay = Playfair_Display({
  variable: "--font-elicyon",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});

// Closest match to Elicyon's body font (__antiqueLegacy_623eb9)
const ebGaramond = EB_Garamond({
  variable: "--font-antique",
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} ${playfairDisplay.variable} ${ebGaramond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
