import { Geist, Geist_Mono, Cormorant_Garamond, EB_Garamond } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const antiqueFont = EB_Garamond({
  variable: "--font-antique",
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal"],
});

const elicyonFont = localFont({
  src: "../fonts/elicyon.woff2",
  variable: "--font-elicyon",
  weight: "400",
  style: "normal",
});

const antiqueCustom = localFont({
  src: "../../public/fonts/Antique/Antique.ttf",
  variable: "--font-nav-menu-local",
  weight: "400",
  style: "normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} ${elicyonFont.variable} ${antiqueFont.variable} ${antiqueCustom.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
